### ISSUE TITLE
Free downloads shouldn't increment a member's download count

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-edd-member-downloads#18]
From a customer:

> Becouse if you put a membership with 2 download at month, and there are free products in your web, and when they downlaod a free product the have one less purchase, it's not make sense.

**Comment by mindctrl** [comment]
I'm not sure I fully agree with the customer. If products are restricted and require a membership to access, the price doesn't necessarily matter. If the site owner wants to control the download count, the price of the item may not matter at all.

We could consider adding an option to count free downloads or not, but since the plugin doesn't have any options at all right now, where would we put it?

Have we had any other requests for this?

**Comment by nosegraze** [comment]
I think this happens even when the product is not restricted. So it's a free product, publicly available, no restrictions, but downloading it counts towards their allowance. If they were to _log out_ they'd be able to download it totally free.

**Comment by mindctrl** [comment]
Yes, it does happen if it's restricted or not. We could check to see if it's restricted first before counting it, but I don't think we can safely make that assumption. Maybe the products are free and unrestricted but download button is wrapped in some code to hide it unless someone has a membership, but they still want to count it towards the limit. I think the only safe way to handle this is to add an option to count free products or not.

**Comment by nosegraze** [comment]
I would be happy with just closing this in favour of https://github.com/restrictcontentpro/rcp-edd-member-downloads/issues/1 and telling people to exclude any free downloads.

**Comment by mindctrl** [comment]
That's a better idea I think!
