### ISSUE TITLE
Add support for specific file/types/volume

### ISSUE THREAD

**Issue by TerenceMilbourn** [restrictcontentpro/rcp-edd-member-downloads#23]
The idea is to give one RCP subscription level the ability to access EDD Member Downloads, not by volume, but by file type, or by filename specifically, or by volume of a specific file type?

**Comment by mindctrl** [comment]
EDD stores file info in a format that's sensible for its use case, but for this type of use case it's not really ideal. And what would happen if a product had more than one file type attached?

@TerenceMilbourn can you explain your use case in more detail?

**Comment by TerenceMilbourn** [comment]
What would happen?  Only the definde file type could be downloaded.

The use case I had imagined was, say, variable "how-to" .PDF files, which might be added to in order build a library over time, which you might want to provide access to, based on the relevant Subscription Level.

**Comment by nosegraze** [comment]
Instead of support for specific file types, I'd prefer something kind of like this: https://github.com/restrictcontentpro/rcp-edd-member-downloads/issues/1 Or maybe, a slight modification of that, the ability to grant access only to certain categories of downloads. For example: you get 10 downloads in the category _"How-To Files"_ only. Then it would be up to you to categorize your PDF downloads in the same category.

**Comment by mindctrl** [comment]
I was thinking categories, or tags, too. I don't think getting into the file type will be a good experience, and some folks attach multiple file types to their products. I don't think it would be a good idea to allow them to download a .pdf from a product but not a .zip attached to it.

**Comment by TerenceMilbourn** [comment]
File categories or tags would work in my scenario.
